server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/gestion_rol
    username: postgres
    password: 123